name: Cron Test
on:
  schedule:
    - cron: "23 2 * * *"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "SCHEDULE EVENT: ${{ github.event_name }} at $(date -u)"
